services:
  openssh-server:
    image: shared-science/ssdaemon
    build: .
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel
      - KHARON_SERVER=http://host.docker.internal:8000
      - KHARON_API_KEY=ss-5fSsI5dYIRbrwKMkED-RQ9cAJQHamU9vhy8PunGnjbI
      - KHARON_REMOTE_HOST=host.docker.internal
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD_ACCESS=false #optional
      - USER_NAME=shared #optional
    volumes:
      - .cache:/cache
    ports:
      - 2222:2222
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
